sudo: true
dist: trusty

language: cpp
compiler:
  - gcc

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5.0" CC="gcc-5.0"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - valgrind
    - libboost1.55-all-dev
script:
  - cmake .
  - make -j4
  - make testsuite_converter
  - ctest
  - bash testValgrind.sh
  - bash runTestsuite.sh
