sudo: true
dist: trusty

language: cpp
compiler:
  - gcc
  - clang

before_install:
  - if [ ${CC} == "clang" ]; then
    export CC=/usr/bin/clang-3.6 CXX=/usr/bin/clang++-3.6;
    fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - clang-3.6
      - valgrind
      - libboost1.55-all-dev

script:
  - cmake .
  - make -j4
  - make testsuite_converter
  - ctest
  - bash testValgrind.sh
  - bash runTestsuite.sh
